## Algerian forest fires-Temperature Prediction 

1)Linear regression model
2)Ridge regression
3)Lasso Regression
4)Elastic-Net Regression

In [ ]:
Dataset-"https://archive.ics.uci.edu/ml/datasets/Algerian+Forest+Fires+Dataset++"

### Importing Libraries 

In [258]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

import warnings
warnings.filterwarnings('ignore')

### Reading the dataset 

In [170]:
df=pd.read_csv(r"D:\Downloads\Algerian_forest_fires_dataset_UPDATE.csv",header=1)
df

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
0    01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4   
1    02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9   
2    03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7   
3    04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7   
4    05    06  2012          27  77  16     0  64.8    3  14.2  1.2   3.9   
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...   
241  26    09  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
242  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
243  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
244  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
245  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI     Classes    
0    0.5   not fire     
1    0.4   not fire     
2    0.1   not fire     
3      0   not fire     
4    0.5   not fire     
..   ...           ...  
241  6.5       fire     
242    0   not fire     
243  0.2   not fire     
244  0.7   not fire     
245  0.5  not fire      

[246 rows x 14 columns]

### Data Cleaning 

#As from the dataset ,it seems that on heading "Bejaia Region Dataset" and "Sidi-Bel Abbes Region Dataset" was included ,so lets remove it and replace it with 0 and 1

In [171]:
df.isnull().sum()#Here we see one empty rows from the dataset,lets remove it completely

day            0
month          1
year           1
Temperature    1
 RH            1
 Ws            1
Rain           1
FFMC           1
DMC            1
DC             1
ISI            1
BUI            1
FWI            1
Classes        2
dtype: int64

In [172]:
df[120:130]

day  month  year  Temperature   RH   Ws  Rain   \
120                             29     09  2012           26   80   16    1.8   
121                             30     09  2012           25   78   14    1.4   
122  Sidi-Bel Abbes Region Dataset    NaN   NaN          NaN  NaN  NaN    NaN   
123                            day  month  year  Temperature   RH   Ws  Rain    
124                             01     06  2012           32   71   12    0.7   
125                             02     06  2012           30   73   13      4   
126                             03     06  2012           29   80   14      2   
127                             04     06  2012           30   64   14      0   
128                             05     06  2012           32   60   14    0.2   
129                             06     06  2012           35   54   11    0.1   

     FFMC  DMC    DC  ISI  BUI  FWI    Classes    
120  47.4  2.9   7.7  0.3    3  0.1  not fire     
121    45  1.9   7.5  0.2  2.4  0.1  not fire     
122   NaN  NaN   NaN  NaN  NaN  NaN          NaN  
123  FFMC  DMC    DC  ISI  BUI  FWI    Classes    
124  57.1  2.5   8.2  0.6  2.8  0.2  not fire     
125  55.7  2.7   7.8  0.6  2.9  0.2  not fire     
126  48.7  2.2   7.6  0.3  2.6  0.1  not fire     
127  79.4  5.2  15.4  2.2  5.6    1  not fire     
128  77.1    6  17.6  1.8  6.5  0.9  not fire     
129  83.7  8.4  26.3  3.1  9.3  3.1      fire

Observation: As we can see on 122 rows all the nan values is present that is nothing but blank rows and on 123rd rows we can see all the header terms so lets remove it

In [173]:
df.drop([122,123],inplace=True)
df.reset_index(inplace=True)
df.drop('index',axis=1,inplace=True)

### so lets make one more columns and lets replace 2 terms "Bejaia Region Dataset" and "Sidi-Bel Abbes Region Dataset"

In [174]:
df.loc[:122,'Region']="Bejaia"
df.loc[122:,'Region']="Sidi-Bel Abbes"
df

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
0    01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4   
1    02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9   
2    03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7   
3    04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7   
4    05    06  2012          27  77  16     0  64.8    3  14.2  1.2   3.9   
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...   
239  26    09  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
240  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
241  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
242  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
243  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI     Classes            Region  
0    0.5   not fire             Bejaia  
1    0.4   not fire             Bejaia  
2    0.1   not fire             Bejaia  
3      0   not fire             Bejaia  
4    0.5   not fire             Bejaia  
..   ...           ...             ...  
239  6.5       fire     Sidi-Bel Abbes  
240    0   not fire     Sidi-Bel Abbes  
241  0.2   not fire     Sidi-Bel Abbes  
242  0.7   not fire     Sidi-Bel Abbes  
243  0.5  not fire      Sidi-Bel Abbes  

[244 rows x 15 columns]

In [175]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        1
Region         0
dtype: int64

In [176]:
df['Classes  '].fillna(df['Classes  '].mode()[0],inplace=True)
df.head()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

     Classes    Region  
0  not fire     Bejaia  
1  not fire     Bejaia  
2  not fire     Bejaia  
3  not fire     Bejaia  
4  not fire     Bejaia

In [177]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Region         0
dtype: int64

In [178]:
df['Classes  '].unique()

array(['not fire   ', 'fire   ', 'fire', 'fire ', 'not fire', 'not fire ',
       'not fire     ', 'not fire    '], dtype=object)

In [179]:
df['Classes  '].replace(['not fire ', 'fire '],
                        [0, 1], inplace=True)

In [180]:
df['Classes  '].replace(['not fire    ', 'not fire     '],
                        [0, 0], inplace=True)

In [181]:
df['Classes  '].unique()

array(['not fire   ', 'fire   ', 'fire', 1, 'not fire', 0], dtype=object)

In [182]:
df['Classes  '].replace(['not fire   ', 'fire   '],
                        [0, 1], inplace=True)

In [183]:
df['Classes  '].replace(['not fire', 'fire'],
                        [0, 1], inplace=True)

In [184]:
df['Classes  '].unique()

array([0, 1], dtype=int64)

In [185]:
df.head()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

   Classes    Region  
0          0  Bejaia  
1          0  Bejaia  
2          0  Bejaia  
3          0  Bejaia  
4          0  Bejaia

In [186]:
df['year'].unique()

array(['2012'], dtype=object)

In [187]:
df['month'].unique()

array(['06', '07', '08', '09'], dtype=object)

In [188]:
df['date']=pd.to_datetime(df[['day','month','year']])

In [189]:
df.drop(['day','month','year'],axis=1,inplace=True)

In [190]:
df.head()

Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  Classes    \
0          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5          0   
1          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4          0   
2          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1          0   
3          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0          0   
4          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5          0   

   Region       date  
0  Bejaia 2012-06-01  
1  Bejaia 2012-06-02  
2  Bejaia 2012-06-03  
3  Bejaia 2012-06-04  
4  Bejaia 2012-06-05

### Changing datatype 

In [191]:
df.info()#As the datatype is stored in dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   Temperature  244 non-null    object        
 1    RH          244 non-null    object        
 2    Ws          244 non-null    object        
 3   Rain         244 non-null    object        
 4   FFMC         244 non-null    object        
 5   DMC          244 non-null    object        
 6   DC           244 non-null    object        
 7   ISI          244 non-null    object        
 8   BUI          244 non-null    object        
 9   FWI          244 non-null    object        
 10  Classes      244 non-null    int64         
 11  Region       244 non-null    object        
 12  date         244 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(11)
memory usage: 24.9+ KB


In [192]:
df.columns#some of the columns contains spaces so lets remove it and change datatype

Index(['Temperature', ' RH', ' Ws', 'Rain ', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes  ', 'Region', 'date'],
      dtype='object')

In [193]:
df.rename(columns={'Rain ':'Rain'},inplace=True)
df.rename(columns={' RH':'RH'},inplace=True)
df.rename(columns={' Ws':'Ws'},inplace=True)
df.rename(columns={'Classes  ':'Classes'},inplace=True)

In [194]:
df.columns

Index(['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes', 'Region', 'date'],
      dtype='object')

In [195]:
df=df.astype({'Temperature':int, 'RH':int, 'Ws':int})
df=df.astype({'Rain':float, 'FFMC':float, 'DMC':float})

In [196]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   Temperature  244 non-null    int32         
 1   RH           244 non-null    int32         
 2   Ws           244 non-null    int32         
 3   Rain         244 non-null    float64       
 4   FFMC         244 non-null    float64       
 5   DMC          244 non-null    float64       
 6   DC           244 non-null    object        
 7   ISI          244 non-null    object        
 8   BUI          244 non-null    object        
 9   FWI          244 non-null    object        
 10  Classes      244 non-null    int64         
 11  Region       244 non-null    object        
 12  date         244 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int32(3), int64(1), object(5)
memory usage: 22.0+ KB


### Numerical categorical columns 

In [197]:
numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print("Numerical feature",numeric_features)
print("categorical feature",categorical_features)

Numerical feature ['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'Classes', 'date']
categorical feature ['DC', 'ISI', 'BUI', 'FWI', 'Region']


In [198]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder=LabelEncoder()

In [199]:
df['DC']=LabelEncoder.fit_transform(df['DC'])
df['FWI']=LabelEncoder.fit_transform(df['FWI'])
df['Region']=LabelEncoder.fit_transform(df['Region'])

In [ ]:
For data vizualization and data Analytics refer-https://github.com/sharanyamanohar/Exploratory-data-analysis/blob/main/Algerian_Forest_fires.ipynb

## Model building 

In [200]:
X=pd.DataFrame(df, columns=['RH','Ws','Rain','FFMC','DMC','DC','ISI','BUI','FWI','Region'])
Y=df['Temperature']

In [201]:
X.head()

RH  Ws  Rain  FFMC  DMC   DC  ISI  BUI  FWI  Region
0  57  18   0.0  65.7  3.4  150  1.3  3.4    5       0
1  61  13   1.3  64.4  4.1  150    1  3.9    4       0
2  82  22  13.1  47.1  2.5  146  0.3  2.7    1       0
3  89  13   2.5  28.6  1.3  136    0  1.7    0       0
4  77  16   0.0  64.8  3.0   18  1.2  3.9    5       0

In [202]:
Y.head()

0    29
1    29
2    26
3    25
4    27
Name: Temperature, dtype: int32

## Scaling the data 

In [218]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()  ## Initialising

In [219]:
scaler

StandardScaler()

## Linear Regression model 

In [ ]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 

In [220]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
X,Y,test_size=0.30,random_state=10)

In [221]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [222]:
lr = LinearRegression()  
lr.fit(X_train, y_train) 
predict_value=lr.predict(X_test)
predict_value

array([31.26744288, 33.44903222, 33.6016886 , 32.09580108, 32.80541768,
       34.92214679, 33.08014461, 33.95269918, 32.00193418, 32.97261884,
       33.41402954, 27.50226278, 34.97716253, 29.09098382, 31.36292754,
       32.44848329, 34.22130494, 28.06054012, 36.24631023, 33.94492719,
       32.51298359, 34.38378597, 33.07388419, 33.18406655, 36.21356315,
       29.75537216, 31.5111502 , 32.32007626, 27.56291422, 32.41404492,
       25.84604424, 27.3002668 , 33.9681096 , 31.46775099, 32.71441237,
       31.25350928, 29.1841298 , 33.0595404 , 27.77194327, 35.58373433,
       33.01186504, 33.66811362, 34.27938894, 31.7647373 , 36.03369651,
       33.57541675, 23.96790699, 35.50766795, 33.76196433, 30.10498808,
       31.28900609, 32.39425507, 35.86786553, 32.27210502, 30.36586898,
       30.27097747, 32.1748406 , 35.95700459, 31.11294526, 33.66856316,
       32.02084337, 32.95946776, 30.65335316, 24.15156908, 31.39532485,
       36.49375064, 30.17254894, 29.59110773, 35.12756633, 33.97

In [223]:
df_value = pd.DataFrame({'Actual': y_test, 'Predicted': predict_value})  
df_value

Actual  Predicted
162      34  31.267443
60       35  33.449032
61       36  33.601689
63       35  32.095801
69       35  32.805418
..      ...        ...
142      32  33.975265
32       32  28.176695
242      24  32.601168
7        30  32.005178
243      24  31.627911

[74 rows x 2 columns]

In [224]:
lr.score(X_train, y_train)

0.5653440207415419

In [225]:
lr.coef_

array([-1.08163596, -0.56015611, -0.29931901,  0.87202714, -1.19195722,
       -0.30083186,  0.37170519,  1.37938633,  0.08022163,  0.2261786 ])

In [226]:
lr.intercept_

32.12352941176471

In [227]:
#Residuals
Residual=y_test-predict_value
Residual

162    2.732557
60     1.550968
61     2.398311
63     2.904199
69     2.194582
         ...   
142   -1.975265
32     3.823305
242   -8.601168
7     -2.005178
243   -7.627911
Name: Temperature, Length: 74, dtype: float64

### Performance Matrix 

In [228]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y_test,predict_value))
print(mean_absolute_error(y_test,predict_value))
print(np.sqrt(mean_squared_error(y_test,predict_value)))

7.320749043202987
2.235855798870343
2.7056882753197913


## R2 value 

In [229]:
from sklearn.metrics import r2_score
score=r2_score(y_test,predict_value)
print(score)

0.5106453563728524


## Adjusted r2 value 

In [230]:
1-(1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.432970016114575

### Ridge Regression model 

In [231]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge_regressor=Ridge()
parameters={'alpha':[1,2,5,10,20,30,40,50,60,70,80,90]}
ridgecv=GridSearchCV(ridge_regressor,parameters,scoring='neg_mean_squared_error',cv=5)
ridgecv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80,
                                   90]},
             scoring='neg_mean_squared_error')

In [232]:
print(ridgecv.best_params_)

{'alpha': 40}


In [233]:
print(ridgecv.best_score_)

-6.065446856933837


In [235]:
ridge_pred=ridgecv.predict(X_test)
ridge_pred

array([31.1007926 , 33.18083146, 33.22572808, 32.01697889, 32.83963366,
       34.58890536, 32.72295679, 33.27269203, 32.06425538, 32.99251332,
       33.5065634 , 27.89542106, 34.5453357 , 29.06266376, 31.230656  ,
       32.64739575, 33.87825734, 28.43243346, 36.07240154, 34.16403381,
       32.46803331, 33.74659884, 32.96333064, 33.36529688, 35.94005415,
       30.08155601, 31.32793567, 32.12213818, 28.03159803, 32.24409225,
       26.39801908, 27.77629391, 33.85928223, 31.24150591, 32.67340806,
       31.09488494, 29.39337917, 32.89497144, 28.21392958, 34.96236544,
       32.78746921, 33.81637488, 34.22477505, 31.69418409, 35.62308798,
       33.36383479, 24.5037668 , 35.26198279, 33.74658554, 30.27139609,
       31.35347861, 32.47261073, 35.86444971, 32.21942322, 30.78022044,
       30.26831531, 32.51365793, 35.80511814, 31.35813013, 33.39573152,
       31.93509292, 32.71929994, 30.67204716, 24.65233236, 31.37896099,
       35.972128  , 30.63354523, 29.66673888, 35.06115796, 33.79

### a)Performance matrix 

In [236]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y_test,ridge_pred))
print(mean_absolute_error(y_test,ridge_pred))
print(np.sqrt(mean_squared_error(y_test,ridge_pred)))

7.357204796765089
2.280367790794584
2.712416781537286


### b) R2 value 

In [238]:
from sklearn.metrics import r2_score
ridge_score=r2_score(y_test,ridge_pred)
print(ridge_score)

0.5082084756401213


### c) Adjusted r2 value 

In [239]:
1-(1-ridge_score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.430146328916331

## Lasso Regression 

In [240]:
from sklearn.linear_model import Lasso
lasso=Lasso()
parameters={'alpha':[1,2,5,10,20,30,40,50,60,70,80,90]}
lassocv=GridSearchCV(lasso,parameters,scoring='neg_mean_squared_error',cv=5)
lassocv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80,
                                   90]},
             scoring='neg_mean_squared_error')

In [241]:
print(lassocv.best_score_)

-7.427411468750945


In [242]:
lasso_pred=lassocv.predict(X_test)
lasso_pred

array([32.16610216, 32.72386046, 32.86349603, 32.02459106, 32.92829129,
       33.30299639, 33.28212734, 32.6560559 , 32.18915933, 32.74805139,
       33.14694741, 30.23204106, 33.94348911, 30.87804378, 32.92641576,
       32.4117625 , 32.8614245 , 29.25483028, 34.2879847 , 33.44513267,
       32.4979354 , 33.04654923, 33.26821464, 32.84180581, 34.3572356 ,
       30.3140709 , 32.35122689, 32.69685624, 29.34557541, 32.02709176,
       29.39094797, 28.45610046, 33.17446022, 32.54444173, 32.68907871,
       31.78870036, 30.20816272, 32.52877009, 29.09545942, 33.54916532,
       32.64796579, 33.21287644, 33.79865613, 31.95690309, 33.93414865,
       33.18505104, 29.70034922, 33.68766713, 33.19896374, 30.68244482,
       31.75911602, 32.44623166, 33.8022906 , 32.28955751, 31.72527204,
       31.23281759, 32.33461748, 34.1213449 , 31.76024979, 33.39280375,
       32.28228857, 32.33918972, 31.2521237 , 29.24849911, 32.17368369,
       34.29130658, 31.34661988, 31.32594684, 33.30299639, 32.99

### a)Evaluation of metrics 

In [243]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y_test,lasso_pred))
print(mean_absolute_error(y_test,lasso_pred))
print(np.sqrt(mean_squared_error(y_test,lasso_pred)))

8.901708219482831
2.5214631986737728
2.983573062534724


### R2 squared 

In [257]:
from sklearn.metrics import r2_score
Lasso_score=r2_score(y_test,lasso_pred)
print(Lasso_score)

0.40496631864982136


### Adjusted R2 squared 

In [245]:
1-(1-Lasso_score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.31051652795931683

## Elastic-Net regression 

In [246]:
from sklearn.linear_model import ElasticNet
elastic_net_reg=ElasticNet()
elastic_net_reg

ElasticNet()

In [249]:
elastic_net_reg.fit(X_train,y_train)
parameters={'alpha':[1,2,5,10,20,30,40,50,60,70,80,90]}
elastic_netcv=GridSearchCV(elastic_net_reg,parameters,scoring='neg_mean_squared_error',cv=5)
elastic_netcv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80,
                                   90]},
             scoring='neg_mean_squared_error')

In [250]:
print(elastic_netcv.best_score_)

-7.030820812594652


In [251]:
elastic_net_pred=elastic_netcv.predict(X_test)

### Metrics Evaluation 

In [253]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y_test,elastic_net_pred))
print(mean_absolute_error(y_test,elastic_net_pred))
print(np.sqrt(mean_squared_error(y_test,elastic_net_pred)))

8.136431636721168
2.391436890501567
2.8524430996465413


### R2 value 

In [255]:
from sklearn.metrics import r2_score
elastic_net_score=r2_score(y_test,elastic_net_pred)
print(elastic_net_score)

0.4561211454610524


### Adjusted R2 value 

In [256]:
1-(1-elastic_net_score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.3697911685501084