Problem Statement-From the wine dataset we tested the quality of wine by using different classification algorithm such as Logistic Regression,Support vector Classifier,Grid Search CV

### Importing Libraries 

Dataset-https://archive.ics.uci.edu/ml/datasets/wine

In [1]:
import numpy as np
import pandas as pd

from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split,GridSearchCV

In [2]:
df=pd.read_csv(r"D:\Downloads\winequality-red.csv",sep=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df['quality'].unique()#All the unique values on that quality column

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [4]:
df.columns#Displaying all the columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [5]:
df.info()#Since there is no null values ,no need to handle any null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


# Train and Test split

In [6]:
x=df.drop('quality',axis=1)#Taking X value
y=df['quality']#Taking Y value

In [7]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [8]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)#Train and test split

# Feature Scaling

In [10]:
scaler=StandardScaler()#Scaling the data 

In [11]:
scaler.fit(x_train,y_train)#Fit the value of x_train and y_train

StandardScaler()

# Support vector Classification

In [12]:
x_train_tf=scaler.transform(x_train)#Trnasforming the data value of x_train

In [13]:
x_test_tf=scaler.transform(x_test)#Transforming the data value of x_test

In [14]:
model=SVC()#Created the SVC model

In [15]:
model.fit(x_train_tf,y_train)#Fitting the transform data inside the model

SVC()

In [16]:
model.score(x_train_tf,y_train)#Checking the score of trained data

0.6778711484593838

In [17]:
pred=model.predict(x_test_tf)#prediction
pred

array([5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 7, 5, 6, 7, 5, 5, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5,
       6, 6, 6, 6, 5, 6, 5, 5, 6, 7, 5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 7, 5,
       6, 5, 7, 5, 6, 5, 6, 6, 6, 5, 7, 5, 6, 7, 5, 7, 5, 5, 6, 6, 5, 6,
       6, 5, 6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6,
       6, 6, 5, 6, 5, 6, 7, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 7, 6,
       6, 5, 5, 5, 5, 7, 5, 7, 5, 6, 6, 6, 7, 5, 6, 6, 5, 6, 6, 5, 5, 5,
       6, 6, 5, 5, 5, 5, 7, 6, 5, 5, 6, 6, 7, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5,
       6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 7,
       6, 7, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 7, 5, 5, 5, 5, 6,
       5, 6, 5, 6, 5, 7, 6, 5, 5, 6, 5, 6, 6, 7, 5,

In [18]:
df_value = pd.DataFrame({'Actual': y_test, 'Predicted': pred})  
df_value

Actual  Predicted
803        6          5
124        5          5
350        6          6
682        5          5
1326       6          6
...      ...        ...
813        4          6
377        7          7
898        7          7
126        5          5
819        5          5

[528 rows x 2 columns]

In [19]:
accuracy_score(y_test,pred)#By scaling the data and by svc algorithm we got only 59% accuracy

0.5984848484848485

### Logistic Regression 

In [20]:
Log_model=LogisticRegression()#Created the logistic model

In [21]:
Log_model.fit(x_train_tf,y_train)#Fitting the data inside model

LogisticRegression()

In [22]:
Log_model.score(x_train_tf,y_train)#Finding the score of trained data

0.6218487394957983

In [23]:
pred_log=Log_model.predict(x_test_tf)#Prediction
pred_log

array([5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 7, 5, 5, 7, 5, 5, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5,
       6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 7, 5,
       7, 5, 6, 5, 7, 5, 6, 6, 6, 5, 7, 6, 6, 7, 5, 7, 5, 6, 6, 6, 5, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5,
       7, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6,
       6, 6, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6,
       6, 5, 5, 5, 5, 6, 5, 7, 5, 6, 6, 6, 7, 5, 6, 6, 6, 6, 6, 5, 5, 5,
       5, 6, 5, 5, 5, 5, 7, 6, 5, 5, 6, 6, 6, 5, 6, 6, 7, 6, 5, 5, 6, 5,
       5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5,
       6, 6, 5, 5, 6, 5, 7, 5, 5, 6, 5, 5, 4, 5, 6, 6, 6, 7, 6, 6, 5, 7,
       6, 6, 5, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 7, 5, 5, 5, 5, 6,
       5, 6, 5, 6, 5, 7, 5, 5, 5, 6, 5, 6, 6, 7, 5,

In [24]:
accuracy_score(y_test,pred_log)#By accuracy score I got 57% only by Logistic Regression

0.571969696969697

In [25]:
df_value = pd.DataFrame({'Actual': y_test, 'Predicted': pred_log})  
df_value

Actual  Predicted
803        6          5
124        5          5
350        6          6
682        5          5
1326       6          6
...      ...        ...
813        4          6
377        7          7
898        7          7
126        5          3
819        5          5

[528 rows x 2 columns]

# GridSearch CV

In [26]:
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(x_train_tf,y_train)

SVC(kernel='linear', random_state=0)

In [27]:
classifier.score(x_train_tf,y_train)

0.6013071895424836

In [43]:
parameters=[{'C':[1,10,20],'kernel':['linear']},{'C':[1,10,20],'kernel':['rbf'],'gamma':[0.6,0.7,0.8,0.9,0.10]}]
grid_search=GridSearchCV(estimator=classifier,param_grid=parameters,scoring='accuracy',cv=5,n_jobs=-1)
grid_search=grid_search.fit(x_train_tf,y_train)

In [44]:
grid_search.best_params_

{'C': 20, 'gamma': 0.8, 'kernel': 'rbf'}

In [81]:
accuracy1=accuracy_score(y_test,classifier1_pred)
accuracy1

0.6193181818181818

In [ ]:
#By gridsearch CV ,I created 2 model in which by classifier1 I got 63%accuracy

In [ ]:
classifier1=SVC(kernel='rbf',gamma=0.8,C=9)
classifier1.fit(x_train_tf,y_train)

In [ ]:
classifier1_pred=classifier1.predict(x_test_tf)

In [47]:
parameters=[{'C':[1,10,20],'kernel':['linear']},{'C':[1,8,9,10,20],'kernel':['rbf'],'gamma':[0.7,0.9,0.10]}]
grid_search1=GridSearchCV(estimator=classifier1,param_grid=parameters,scoring='accuracy',cv=5,n_jobs=-1)
grid_search1=grid_search1.fit(x_train_tf,y_train)

In [48]:
grid_search1.best_params_

{'C': 9, 'gamma': 0.7, 'kernel': 'rbf'}

In [35]:
accuracy=grid_search.best_score_
accuracy

0.6386611606172571